version: "3.1"

services:
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: gndprodesk
        ports:
            - 5432:5432
    # postgres:
    #     build: postgres-with-pgloader
    #     container_name: postgres-db
    #     ports:
    #         - "5431:5432"
    #     restart: always
    #     volumes:
    #         - db_data:/var/lib/postgresql/data
    #     environment:
    #         POSTGRES_PASSWORD: root
    # mysql:
    #     image: mysql:5.7
    #     container_name: mysql-db
    #     ports:
    #         - "3307:3306"
    #     volumes:
    #         - /var/lib/mysql
    #         - ./migrations:/docker-entrypoint-initdb.d
    #     environment:
    #         MYSQL_DATABASE: database
    #         MYSQL_USER: user
    #         MYSQL_PASSWORD: password
    #         MYSQL_ROOT_PASSWORD: root_password
    # volumes:
    #     db_data:
    # pgadmin:
    #   container_name: pgadmin4_container
    #   image: dpage/pgadmin4
    #   restart: always
    #   environment:
    #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
    #     PGADMIN_DEFAULT_PASSWORD: root
    #   ports:
    #     - "5050:80"

    # adminer:
    #   image: adminer
    #   restart: always
    #   ports:
    #     - 8080:8080
